import { Dimensions, StatusBar, StyleSheet } from "react-native";
import { normalizeFontSize } from "./utils";

export const screenHeight = Dimensions.get("screen").height;
export const windowHeight = Dimensions.get("window").height;
export const mainColor = "#4286F5";
export const secondaryColor = "#F5B142";
export const tertiaryColor = "#F542DF";
export const quaternaryColor = "#42F557";
export const backgroundColor = "#000000";

export const header = 70;
export const footer = 60;
export const ratio =
  Dimensions.get("window").height / Dimensions.get("window").width;
export const main =
  Dimensions.get("window").height -
  (header + footer + (ratio > 1.7 ? 0 : (StatusBar.currentHeight ?? 0)));
export const StatusBarHeight = StatusBar.currentHeight ?? 0;
export const NavigatorBarHeight = screenHeight - windowHeight;

// ─── Utility Constants ──────────────────────────────────────────────────────
export const whiteColor = "#ffffff";
export const grayColor = "#8a8a8e";
export const lightGrayColor = "#9CA3AF";
export const darkGrayColor = "#1F2937";
export const transparentBlack = "rgba(0, 0, 0, 0.7)";
export const transparentWhite = "rgba(255, 255, 255, 0.05)";

/**
 * Creates a reactive GlobalStyles object.
 * Every property is a function that takes { width, height, scale, normalize }
 */
export const createGlobalStyles = ({ normalize }) => {
  const baseCenter = { justifyContent: "center", alignItems: "center" };
  const baseRow = { flexDirection: "row", alignItems: "center" };
  const baseText = { color: whiteColor, fontFamily: "Exo2_400Regular" };
  const baseBoldText = { ...baseText, fontFamily: "Exo2_700Bold" };
  const baseModal = {
    backgroundColor: "#111111",
    borderRadius: normalize(25),
    padding: normalize(24),
    ...baseCenter,
    width: "90%",
  };
  const baseButton = {
    borderRadius: normalize(50),
    padding: normalize(10),
    width: "100%",
    ...baseCenter,
    borderWidth: 2,
  };
  const baseInput = {
    borderRadius: normalize(5),
    borderColor: secondaryColor,
    borderWidth: 2,
    color: "black",
    backgroundColor: "white",
    textAlign: "center",
    height: normalize(50),
    fontSize: normalize(24),
    width: "100%",
    marginVertical: 1,
  };
  const baseShadow = {};
  const brutalShadow = {};
  const brutalBorder = {
    borderWidth: 2,
    borderColor: "#FFFFFF",
  };

  return StyleSheet.create({
    // ─── Layout Utilities ─────────────────────────────────────────────────────
    row: { flexDirection: "row" },
    rowCenter: baseRow,
    rowBetween: { ...baseRow, justifyContent: "space-between" },
    centerAll: baseCenter,
    flex1: { flex: 1 },
    w100: { width: "100%" },
    h100: { height: "100%" },
    fullScreenCentered: { flex: 1, ...baseCenter },
    fullScreenCenteredMod: { ...baseCenter },
    // ─── Spacing Utilities ────────────────────────────────────────────────────
    mt10: { marginTop: normalize(10) },
    mt20: { marginTop: normalize(20) },
    mb10: { marginBottom: normalize(10) },
    mb20: { marginBottom: normalize(20) },
    pb40: { paddingBottom: normalize(40) },
    p10: { padding: normalize(10) },
    p20: { padding: normalize(20) },
    ph5: { paddingHorizontal: "5%" },
    ph10: { paddingHorizontal: normalize(10) },
    ph20: { paddingHorizontal: normalize(20) },
    // ─── Text Utilities ───────────────────────────────────────────────────────
    textWhite: { color: whiteColor },
    textGray: { color: grayColor },
    textCenter: { textAlign: "center" },
    textBold: { fontWeight: "bold" },
    // ─── Core Layout ──────────────────────────────────────────────────────────
    container: {
      flex: 1,
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor,
    },
    scrollContainer: { width: "100%", height: "auto" },
    header: {
      height: normalize(header),
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      backgroundColor,
    },
    main: {
      flex: 1,
      backgroundColor,
      width: "100%",
      justifyContent: "space-between",
      alignItems: "center",
    },
    footer: {
      width: "100%",
      height: normalize(footer),
      flexDirection: "row",
      borderTopWidth: 0,
      borderTopColor: mainColor,
      justifyContent: "space-between",
    },
    headerItem: { ...baseCenter, width: "50%", height: "100%" },
    mainItem: {
      ...baseRow,
      width: "100%",
      height: "auto",
      justifyContent: "space-between",
    },
    selector: { ...baseCenter, flex: 1, height: "100%" },
    // ─── Typography ───────────────────────────────────────────────────────────
    selectorText: {
      ...baseText,
      fontSize: normalize(14),
      textAlign: "center",
    },
    selectorSelectedText: {
      ...baseText,
      fontSize: normalize(14),
      color: mainColor,
      textAlign: "center",
    },
    balance: { ...baseText, fontSize: normalize(38), marginTop: normalize(10) },
    title: {
      ...baseBoldText,
      fontSize: normalize(26),
      textAlign: "center",
    },
    titlePaymentToken: {
      ...baseBoldText,
      fontSize: normalize(26),
      textAlign: "center",
      marginVertical: normalize(ratio > 1.7 ? 26 : 40),
    },
    description: {
      ...baseBoldText,
      fontSize: normalize(14),
      textAlign: "center",
    },
    formTitle: {
      ...baseBoldText,
      fontSize: normalize(18),
      textAlign: "left",
    },
    formTitleCard: {
      ...baseBoldText,
      fontSize: normalize(24),
      textAlign: "left",
    },
    exoTitle: {
      ...baseBoldText,
      fontSize: normalize(24),
      textAlign: "center",
    },
    // ─── Buttons ──────────────────────────────────────────────────────────────
    buttonSelector: { ...baseCenter, flex: 1, height: "100%" },
    buttonContainer: { width: "100%", gap: normalize(4) },
    buttonStyle: {
      ...baseButton,
      backgroundColor: mainColor,
      borderColor: mainColor,
    },
    buttonCancelStyle: {
      ...baseButton,
      backgroundColor: "black",
      borderColor: "gray",
    },
    buttonText: { ...baseBoldText, fontSize: normalize(24) },
    buttonTextSmall: { ...baseBoldText, fontSize: normalize(20) },
    buttonCancelText: {
      ...baseBoldText,
      fontSize: normalize(24),
      color: "gray",
    },
    singleButton: {
      ...baseCenter,
      backgroundColor: mainColor,
      borderRadius: normalize(50),
      width: normalize(60),
      height: normalize(60),
    },
    singleButtonText: { ...baseText, textAlign: "center" },
    buttonSelectorSelectedStyle: {
      backgroundColor: "#1E2423",
      borderWidth: 2,
      padding: normalize(5),
      alignItems: "center",
      borderColor: mainColor,
      minWidth: "30%",
    },
    // ─── Wallet / Balance ─────────────────────────────────────────────────────
    balanceContainer: {
      ...baseCenter,
      display: "flex",
      justifyContent: "space-evenly",
      height: ratio > 1.7 ? main * 0.47 : main * 0.45,
    },
    tokensContainer: { height: normalize(10), marginBottom: 0 },
    tab3Container: { width: "100%", height: "100%" },
    tab3ScrollContainer: { ...baseCenter, width: "100%", height: "100%" },
    // ─── Network / Token rows ─────────────────────────────────────────────────
    networkShow: {
      ...baseRow,
      justifyContent: "space-between",
      width: "90%",
      height: normalize(60),
      backgroundColor: "#111111",
      borderRadius: normalize(10),
      marginVertical: normalize(10),
    },
    network: {
      ...baseRow,
      justifyContent: "space-between",
      width: "100%",
      height: normalize(66),
      backgroundColor: "#111111",
      borderRadius: normalize(10),
    },
    networkMarginIcon: { marginHorizontal: normalize(10) },
    networkTokenName: { fontSize: normalize(18), color: whiteColor },
    networkTokenNetwork: { fontSize: normalize(12), color: whiteColor },
    networkTokenNetworkIcon: {
      position: "absolute",
      right: normalize(-4),
      top: normalize(-4),
      width: normalize(22),
      height: normalize(22),
      borderRadius: normalize(20),
      borderColor: whiteColor,
      borderWidth: 2,
      overflow: "hidden",
      backgroundColor: whiteColor,
      ...baseCenter,
    },
    networkTokenData: { fontSize: normalize(12), color: whiteColor },
    // ─── Inputs ───────────────────────────────────────────────────────────────
    inputText: { fontSize: normalize(18), textAlign: "center" },
    inputContainer: { width: "100%" },
    picker: baseInput,
    input: baseInput,
    inputChat: {
      ...baseInput,
      borderRadius: normalize(10),
      fontSize: normalize(18),
      padding: normalize(10),
      textAlign: "justify",
      width: "80%",
    },
    // ─── Profile / Tab5 ───────────────────────────────────────────────────────
    profileSection: { alignItems: "center", paddingVertical: normalize(40) },
    avatarContainer: {
      width: normalize(200),
      height: normalize(200),
      borderRadius: normalize(100),
      marginBottom: normalize(30),
      padding: normalize(8),
      backgroundColor: darkGrayColor,
      ...baseShadow,
    },
    avatarGradient: {
      width: "100%",
      height: "100%",
      borderRadius: normalize(92),
    },
    username: {
      ...baseBoldText,
      fontSize: normalize(32),
      marginBottom: normalize(8),
    },
    joinDate: {
      ...baseText,
      fontSize: normalize(16),
      color: lightGrayColor,
    },
    verificationSection: { ...baseRow, marginBottom: normalize(30) },
    verificationBadge: {
      ...baseCenter,
      width: normalize(48),
      height: normalize(48),
      borderRadius: normalize(24),
      backgroundColor: mainColor,
      marginRight: normalize(16),
    },
    verificationText: { flex: 1 },
    verificationLabel: {
      ...baseText,
      fontSize: normalize(14),
      color: lightGrayColor,
    },
    verificationStatus: { ...baseBoldText, fontSize: normalize(20) },
    humanAccessText: {
      ...baseText,
      fontSize: normalize(16),
      color: lightGrayColor,
      textAlign: "left",
      marginBottom: normalize(40),
      paddingLeft: normalize(20),
    },
    actionsSection: { paddingBottom: normalize(40) },
    actionItem: {
      ...baseRow,
      justifyContent: "space-between",
      paddingVertical: normalize(16),
      paddingHorizontal: normalize(20),
      marginBottom: normalize(12),
      backgroundColor: darkGrayColor,
      borderRadius: normalize(12),
    },
    actionLeft: { ...baseRow, flex: 1 },
    actionIcon: { marginRight: normalize(16) },
    worldcoinIcon: {
      ...baseCenter,
      width: normalize(48),
      height: normalize(48),
      borderRadius: normalize(12),
      backgroundColor: mainColor,
    },
    worldcoinText: { ...baseBoldText, fontSize: normalize(20) },
    earnIcon: {
      ...baseCenter,
      width: normalize(48),
      height: normalize(48),
      borderRadius: normalize(12),
      backgroundColor: mainColor,
    },
    earnIconText: { ...baseBoldText, fontSize: normalize(20) },
    actionTextContainer: { flex: 1 },
    actionTitle: {
      ...baseBoldText,
      fontSize: normalize(18),
      marginBottom: normalize(2),
    },
    actionSubtitle: {
      ...baseText,
      fontSize: normalize(14),
      color: lightGrayColor,
    },
    doneButton: {
      ...baseRow,
      backgroundColor: quaternaryColor,
      paddingHorizontal: normalize(16),
      paddingVertical: normalize(8),
      borderRadius: normalize(20),
    },
    doneButtonText: {
      ...baseBoldText,
      fontSize: normalize(14),
      marginLeft: normalize(4),
    },
    // ─── Shared Component Styles ──────────────────────────────────────────────
    topBar: { ...baseRow, justifyContent: "space-between", width: "100%" },
    backButton: { ...baseCenter, width: "20%" },
    actionIconSpaced: { marginLeft: normalize(15), opacity: 0.8 },
    qrContainer: {
      padding: normalize(15),
      backgroundColor: "white",
      borderRadius: normalize(15),
      marginBottom: normalize(20),
    },
    headerTitle: {
      color: whiteColor,
      fontSize: normalize(24),
      fontWeight: "bold",
      marginVertical: normalize(20),
      textAlign: "center",
    },
    cameraRing: {
      width: normalize(280),
      height: normalize(280),
      borderRadius: normalize(140),
      borderWidth: 4,
      ...baseCenter,
      alignSelf: "center",
    },
    cameraInner: {
      width: "100%",
      height: "100%",
      borderRadius: normalize(140),
      overflow: "hidden",
      backgroundColor: "#1c1c1e",
    },
    qrRing: {
      width: normalize(280),
      height: normalize(280),
      borderRadius: normalize(20),
      borderWidth: 4,
      ...baseCenter,
      alignSelf: "center",
      elevation: 10,
    },
    qrInner: {
      width: "100%",
      height: "100%",
      borderRadius: normalize(16),
      overflow: "hidden",
      backgroundColor: "#1c1c1e",
    },
    loadingContainer: {
      height: normalize(20),
      ...baseRow,
      justifyContent: "center",
      gap: normalize(10),
    },
    loadingText: {
      color: secondaryColor,
      fontSize: normalize(16),
      fontWeight: "600",
    },
    captureButton: {
      ...baseRow,
      width: "85%",
      height: normalize(60),
      borderRadius: normalize(30),
      alignSelf: "center",
    },
    buttonGroup: {
      flexDirection: "column",
      alignItems: "center",
      gap: normalize(15),
      width: "100%",
      marginTop: normalize(10),
    },
    scrollContent: {
      width: "90%",
      alignSelf: "center",
      paddingBottom: normalize(40),
      gap: normalize(10),
    },
    screenHeaderContainer: {
      alignItems: "center",
      paddingHorizontal: normalize(10),
    },
    subtitle: {
      color: "#aaa",
      fontSize: normalize(15),
      textAlign: "center",
      lineHeight: normalize(22),
      marginTop: normalize(12),
    },
    amountText: {
      fontSize: normalize(36),
      color: whiteColor,
      textAlign: "center",
      marginVertical: normalize(5),
    },
    addressText: {
      color: whiteColor,
      fontSize: normalize(18),
      fontWeight: "bold",
      textAlign: "center",
    },
    statusText: {
      fontSize: normalize(24),
      fontWeight: "600",
      textAlign: "center",
      marginBottom: normalize(20),
      minHeight: normalize(24),
    },
    secureNote: {
      color: "#666",
      fontSize: normalize(12),
      textAlign: "center",
      marginTop: normalize(10),
    },
    // ─── Modals ───────────────────────────────────────────────────────────────
    backdrop: {
      width: "100%",
      height: "100%",
      ...baseCenter,
    },
    modalOverlay: { backgroundColor: "rgba(0,0,0,0.85)", ...baseCenter },
    modalContainer: {
      ...baseModal,
      minHeight: "70%",
      justifyContent: "space-between",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
      boxShadow: `0px ${normalize(10)}px ${normalize(20)}px rgba(0, 0, 0, 0.5)`,
      elevation: 20,
    },
    modalContent: {
      width: "90%",
      backgroundColor: "#111111",
      borderRadius: normalize(20),
      padding: normalize(20),
      borderWidth: 1,
      borderColor: "#333",
      maxHeight: "90%",
    },
    modalHeader: {
      ...baseRow,
      justifyContent: "space-between",
      width: "100%",
      marginBottom: normalize(20),
    },
    modalTitle: {
      color: whiteColor,
      fontSize: normalize(18),
      fontWeight: "bold",
    },
    modalTitleDetail: {
      color: whiteColor,
      fontSize: normalize(20),
      fontWeight: "bold",
      flex: 1,
      lineHeight: normalize(28),
    },
    modalImage: {
      width: "100%",
      height: "auto",
      minHeight: normalize(180),
      maxHeight: normalize(200),
      borderRadius: normalize(12),
      marginBottom: normalize(15),
      backgroundColor: backgroundColor,
    },
    modalBadgeRow: {
      ...baseRow,
      justifyContent: "space-between",
      paddingBottom: normalize(15),
      borderBottomWidth: 1,
      borderBottomColor: "#222",
      marginBottom: normalize(20),
    },
    modalDateText: {
      color: "#8e8e93",
      fontSize: normalize(14),
      fontWeight: "600",
    },
    modalBodyInfo: {
      backgroundColor: "#161618",
      padding: normalize(16),
      borderRadius: normalize(12),
      gap: normalize(12),
    },
    modalDetailRow: { ...baseRow, gap: normalize(10) },
    modalDetailInfo: {
      color: "#e5e5e7",
      fontSize: normalize(15),
      lineHeight: normalize(22),
      flex: 1,
    },
    // ─── Pass modal specific ───────────────────────────────────────────────────
    descriptionContainer: { paddingHorizontal: normalize(10) },
    assignmentBox: {
      backgroundColor: "rgba(255,255,255,0.03)",
      paddingVertical: normalize(12),
      paddingHorizontal: normalize(20),
      borderRadius: normalize(15),
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
      width: "100%",
      alignItems: "center",
    },
    assignmentLabel: {
      fontSize: normalize(10),
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: normalize(4),
    },
    assignmentText: {
      color: "white",
      fontSize: normalize(14),
      fontWeight: "600",
      textAlign: "center",
    },
    smartSizeContainer: {
      backgroundColor: "rgba(0, 0, 0, 0.85)",
      ...baseCenter,
    },
    pickerBox: {
      ...baseModal,
      padding: normalize(24),
      borderRadius: normalize(16),
      maxHeight: "75%",
      borderWidth: 1,
      borderColor: "#1C1C1E",
      alignItems: "stretch", // Ensures full-width list items
    },
    pickerItem: {
      ...baseRow,
      justifyContent: "space-between",
      paddingVertical: normalize(18),
      paddingHorizontal: normalize(16),
      width: "100%",
      borderRadius: normalize(12),
      marginBottom: normalize(4),
    },
    pickerItemSelected: {
      backgroundColor: "rgba(255, 255, 255, 0.08)",
    },
    pickerItemText: { color: whiteColor, fontSize: normalize(16) },
    pickerItemTextSelected: { color: mainColor, fontWeight: "bold" },
    // ─── Tabs & Screens Specific ──────────────────────────────────────────────
    tab1HeaderContainer: { width: "100%" },
    tabContainer: {
      ...baseRow,
      marginTop: normalize(15),
      backgroundColor: "#1c1c1e",
      borderRadius: normalize(12),
      padding: normalize(4),
      marginBottom: normalize(15),
      marginHorizontal: normalize(15),
    },
    tabButton: {
      flex: 1,
      paddingVertical: normalize(10),
      alignItems: "center",
      borderRadius: normalize(8),
    },
    activeTab: { backgroundColor: "#3a3a3c" },
    tabText: { color: "#8e8e93", fontSize: normalize(14), fontWeight: "700" },
    activeTabText: { color: whiteColor },
    walletGradient: { ...baseCenter, width: "110%", marginTop: normalize(20) },
    walletActionsRow: {
      ...baseRow,
      justifyContent: "space-between",
      width: "100%",
      marginVertical: normalize(12),
    },
    walletActionItem: { alignItems: "center" },
    walletActionIcon: {
      width: normalize(60),
      height: normalize(60),
      borderRadius: normalize(30),
      backgroundColor: "#1c1c1e",
      ...baseCenter,
      marginBottom: normalize(8),
    },
    walletActionLabel: {
      color: whiteColor,
      fontSize: normalize(13),
      fontWeight: "500",
    },
    // ─── Tab4 / Wallet Premium Styles ─────────────────────────────────────────
    tab4ScrollContent: {
      paddingHorizontal: normalize(20),
      paddingTop: normalize(10),
      paddingBottom: normalize(5),
      flexGrow: 1,
    },
    tab4HeaderSection: {
      alignItems: "center",
      marginTop: normalize(10),
      marginBottom: normalize(40),
    },
    tab4BalanceLabel: {
      fontFamily: "Exo2_700Bold",
      color: "#8E8E93",
      fontSize: normalize(12),
      textTransform: "uppercase",
      letterSpacing: 1.5,
    },
    tab4BalanceText: {
      fontFamily: "Exo2_700Bold",
      color: whiteColor,
      fontSize: normalize(42),
      marginVertical: normalize(8),
      letterSpacing: -1,
    },
    tab4ActionsRow: {
      flexDirection: "row",
      justifyContent: "space-around",
      width: "100%",
      marginBottom: normalize(40),
    },
    tab4ActionItem: {
      alignItems: "center",
      width: normalize(70),
    },
    tab4ActionCircle: {
      width: normalize(56),
      height: normalize(56),
      borderRadius: normalize(28),
      backgroundColor: "#1C1C1E",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: normalize(8),
    },
    tab4ActionLabel: {
      fontFamily: "Exo2_400Regular",
      color: whiteColor,
      fontSize: normalize(13),
    },
    tab4AssetCard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: normalize(16),
      backgroundColor: "#1C1C1E",
      borderRadius: normalize(16),
      marginBottom: normalize(12),
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.05)",
    },
    tab4AssetLeft: {
      flex: 1, // Ensures left content doesn't overlap right side
      flexDirection: "row",
      alignItems: "center",
    },
    tab4IconContainer: {
      position: "relative",
      marginRight: normalize(12),
    },
    tab4MainIcon: {
      width: normalize(52),
      height: normalize(52),
      borderRadius: normalize(26),
      overflow: "hidden",
    },
    tab4BadgeContainer: {
      position: "absolute",
      right: normalize(-3),
      bottom: normalize(-3),
      width: normalize(20),
      height: normalize(20),
      borderRadius: normalize(9),
      backgroundColor: "#FFF",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
    },
    tab4AssetInfo: {
      flex: 1,
      justifyContent: "center",
    },
    tab4AssetName: {
      fontFamily: "Exo2_700Bold",
      color: whiteColor,
      fontSize: normalize(18),
    },
    tab4AssetSubtext: {
      fontFamily: "Exo2_400Regular",
      color: "#8E8E93",
      fontSize: normalize(13),
      marginTop: normalize(2),
    },
    tab4AssetRight: {
      alignItems: "flex-end",
      marginLeft: normalize(12), // Minimum gap
      minWidth: normalize(80),   // Ensure space for USD values
    },
    tab4AssetValue: {
      fontFamily: "Exo2_700Bold",
      color: whiteColor,
      fontSize: normalize(17),
    },
    tab4AssetValueSmall: {
      fontFamily: "Exo2_400Regular",
      color: "#8E8E93",
      fontSize: normalize(12),
      marginTop: normalize(2),
    },
    passesScrollContent: { width: "90%", alignSelf: "center", height: "100%" },
    scrollContainerContent: {
      ...baseCenter,
      minHeight: "100%",
      width: "100%",
      justifyContent: "space-evenly",
      gap: normalize(20),
    },
    passesMainTitle: {
      color: whiteColor,
      fontSize: normalize(32),
      fontWeight: "bold",
      marginVertical: normalize(20),
    },
    emptyContainer: { marginTop: normalize(40), alignItems: "center" },
    emptyText: { color: "#666", marginTop: normalize(10) },
    sectionContainer: { marginBottom: normalize(10) },
    categoryButton: {
      ...baseRow,
      justifyContent: "space-between",
      paddingVertical: normalize(16),
      paddingHorizontal: normalize(16),
      backgroundColor: "#1C1C1E",
      borderRadius: normalize(16),
      marginBottom: normalize(4),
    },
    categoryHeaderRow: { ...baseRow, flex: 1 },
    categoryIndicator: {
      width: normalize(4),
      height: normalize(18),
      backgroundColor: mainColor,
      marginRight: normalize(12),
      borderRadius: normalize(2),
    },
    categoryHeader: {
      color: whiteColor,
      fontSize: normalize(14),
      fontFamily: "Exo2_700Bold",
      letterSpacing: -0.2,
    },
    pillBadge: {
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(2),
      borderRadius: normalize(10),
      marginLeft: normalize(10),
    },
    badge: {
      backgroundColor: "#1c1c1e",
      paddingHorizontal: normalize(8),
      paddingVertical: normalize(2),
      borderRadius: normalize(6),
      marginLeft: normalize(10),
    },
    badgeText: {
      color: grayColor,
      fontSize: normalize(10),
      fontWeight: "bold",
    },
    listContainer: { marginTop: normalize(8) },
    passCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#1C1C1E",
      borderRadius: normalize(16),
      marginBottom: normalize(12),
      padding: normalize(16),
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.05)",
    },
    passName: {
      fontFamily: "Exo2_700Bold",
      color: whiteColor,
      fontSize: normalize(18),
      letterSpacing: -0.5,
    },
    passMeta: {
      fontFamily: "Exo2_400Regular",
      color: "#8E8E93",
      fontSize: normalize(13),
      marginTop: normalize(2),
    },
    passImage: {
      width: normalize(55),
      height: normalize(55),
      borderRadius: normalize(12),
    },
    networkBadge: {
      position: "absolute",
      top: normalize(-4),
      right: normalize(-4),
      borderRadius: normalize(11),
      width: normalize(20),
      height: normalize(20),
      backgroundColor: "#FFF",
      ...baseCenter,
      zIndex: 10,
    },
    passInfo: { flex: 1, marginLeft: normalize(15) },
    passName: { color: whiteColor, fontSize: normalize(17), fontWeight: "600" },
    passAction: {
      color: "#636366",
      fontSize: normalize(11),
      marginTop: normalize(4),
    },
    eventsContainer: { flex: 1, width: "100%" },
    pickerButtonsContainer: {
      ...baseRow,
      justifyContent: "space-between",
      gap: normalize(10),
      marginBottom: normalize(10),
      marginHorizontal: normalize(15),
    },
    dropdownButton: {
      ...baseRow,
      justifyContent: "space-between",
      backgroundColor: "#1c1c1e",
      borderRadius: normalize(10),
      padding: normalize(12),
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
    },
    dropdownButtonText: {
      color: whiteColor,
      fontSize: normalize(13),
      fontWeight: "600",
      flex: 1,
    },
    eventsListContainer: {
      width: "94%",
      alignSelf: "center",
      paddingTop: normalize(10),
      paddingBottom: normalize(40),
    },
    eventPassCard: {
      backgroundColor: "#1c1c1e",
      borderRadius: normalize(15),
      marginBottom: normalize(12),
      padding: normalize(16),
      borderWidth: 1,
      borderColor: transparentWhite,
    },
    cardHeader: {
      ...baseRow,
      justifyContent: "space-between",
      marginBottom: normalize(10),
    },
    cardMainContent: { flexDirection: "row", gap: normalize(12) },
    cardThumbnail: {
      width: normalize(60),
      height: normalize(60),
      borderRadius: normalize(8),
      backgroundColor: "#2c2c2e",
    },
    dateText: { color: "#8e8e93", fontWeight: "600", fontSize: normalize(13) },
    categoryBadge: {
      paddingHorizontal: normalize(8),
      paddingVertical: normalize(2),
      borderRadius: normalize(6),
      borderWidth: 1,
    },
    categoryText: {
      fontSize: normalize(10),
      fontWeight: "800",
      textTransform: "uppercase",
    },
    titleText: {
      color: whiteColor,
      fontSize: normalize(17),
      fontWeight: "700",
      marginBottom: normalize(8),
      lineHeight: normalize(22),
    },
    detailRow: { ...baseRow, gap: normalize(6) },
    detailText: { color: "#8e8e93", fontSize: normalize(13) },
    urlButton: {
      ...baseRow,
      backgroundColor: whiteColor,
      paddingVertical: normalize(14),
      borderRadius: normalize(12),
      justifyContent: "center",
      gap: normalize(8),
      marginTop: normalize(15),
    },
    urlButtonText: {
      color: backgroundColor,
      fontSize: normalize(15),
      fontWeight: "bold",
    },
    amenitiesContainer: { flex: 1, width: "100%", backgroundColor: "#f4f6f9" },
    sliderContainer: {
      width: "100%",
      backgroundColor: "white",
      paddingTop: normalize(8),
      paddingBottom: normalize(12),
      zIndex: 10,
      borderBottomWidth: 1,
      borderBottomColor: "#ebebeb",
    },
    catSlider: { height: normalize(90) },
    catCircleWrapper: { marginRight: normalize(8), ...baseCenter },
    catCircle: {
      width: normalize(80),
      height: normalize(80),
      borderRadius: normalize(40),
      backgroundColor: whiteColor,
      ...baseCenter,
      borderWidth: 1,
      borderColor: "#e5e5e5",
    },
    catCircleActive: { borderColor: "#004EA2", borderWidth: 2 },
    catCircleImage: {
      width: normalize(60),
      height: normalize(60),
      borderRadius: normalize(30),
    },
    contentArea: { flex: 1, backgroundColor: "#f4f6f9" },
    amenitiesScrollContent: {
      paddingHorizontal: normalize(16),
      paddingTop: normalize(20),
      paddingBottom: normalize(120),
    },
    bannerContainer: {
      width: "100%",
      height: normalize(210),
      borderTopRightRadius: normalize(30),
      borderTopLeftRadius: normalize(30),
      overflow: "hidden",
      backgroundColor: whiteColor,
    },
    bannerImage: { width: "100%", height: "100%" },
    bannerBadge: {
      position: "absolute",
      top: normalize(12),
      right: normalize(12),
      backgroundColor: "#70c8c0",
      width: normalize(72),
      height: normalize(72),
      borderRadius: normalize(36),
      ...baseCenter,
      ...baseShadow,
    },
    badgeDate: {
      color: whiteColor,
      fontSize: normalize(14),
      fontWeight: "bold",
      textAlign: "center",
      lineHeight: normalize(16),
    },
    infoRowContainer: {
      paddingHorizontal: normalize(16),
      flexDirection: "row",
      alignItems: "flex-start",
    },
    infoIconBg: {
      width: normalize(44),
      height: normalize(44),
      borderRadius: normalize(22),
      ...baseCenter,
      marginRight: normalize(16),
    },
    infoContent: {
      flex: 1,
      justifyContent: "center",
      paddingTop: normalize(2),
    },
    infoTitle: { fontSize: normalize(13), color: "#666" },
    infoValueRow: {
      ...baseRow,
      flexWrap: "wrap",
      gap: normalize(12),
      marginTop: normalize(2),
    },
    infoValue: { fontSize: normalize(17), fontWeight: "bold", color: "#111" },
    infoLink: {
      fontSize: normalize(13),
      color: "#004EA2",
      textDecorationLine: "underline",
    },
    infoStatus: {
      fontSize: normalize(17),
      fontWeight: "bold",
      marginLeft: normalize(-6),
    },
    fullButton: {
      marginHorizontal: normalize(16),
      backgroundColor: "#f8f9fb",
      borderRadius: normalize(12),
      paddingVertical: normalize(18),
      ...baseRow,
      justifyContent: "center",
      gap: normalize(8),
      ...baseShadow,
      elevation: 1,
    },
    fullButtonText: {
      color: "#004EA2",
      fontSize: normalize(15),
      fontWeight: "bold",
    },
    sectionTitle: {
      paddingHorizontal: normalize(16),
      marginVertical: normalize(16),
      fontSize: normalize(19),
      fontWeight: "bold",
      color: "#111",
      marginTop: normalize(20),
    },
    tickerText: {
      color: whiteColor,
      fontSize: normalize(15),
      fontWeight: "bold",
      marginLeft: normalize(12),
      flex: 1,
      lineHeight: normalize(22),
    },
    eventsSubTitle: {
      fontSize: normalize(16),
      fontWeight: "bold",
      color: "#333",
      paddingHorizontal: normalize(16),
      marginBottom: normalize(12),
    },
    eventsScroll: { paddingLeft: normalize(16), overflow: "visible" },
    eventCard: {
      width: normalize(160),
      backgroundColor: whiteColor,
      borderRadius: normalize(12),
      marginRight: normalize(16),
      ...baseShadow,
      elevation: 2,
    },
    eventImage: {
      width: "100%",
      height: normalize(140),
      borderTopLeftRadius: normalize(12),
      borderTopRightRadius: normalize(12),
      backgroundColor: "#f0f0f0",
    },
    eventTextContainer: { padding: normalize(12) },
    eventTitle: {
      fontSize: normalize(15),
      fontWeight: "bold",
      color: "#111",
      marginBottom: normalize(6),
    },
    eventDate: { fontSize: normalize(12), color: "#666" },
    campaignListContainer: { marginBottom: normalize(32) },
    campaignItemsWrapper: {
      paddingHorizontal: normalize(16),
      gap: normalize(12),
    },
    campaignCard: {
      ...baseRow,
      backgroundColor: whiteColor,
      borderRadius: normalize(12),
      padding: normalize(12),
      ...baseShadow,
      elevation: 2,
    },
    campaignImage: {
      width: normalize(130),
      height: normalize(80),
      borderRadius: normalize(8),
    },
    campaignTextContainer: {
      flex: 1,
      marginLeft: normalize(12),
      justifyContent: "center",
    },
    campaignItemTitle: {
      fontSize: normalize(15),
      fontWeight: "bold",
      color: "#111",
      marginBottom: normalize(6),
      lineHeight: normalize(20),
    },
    campaignItemDate: { fontSize: normalize(13), color: "#666" },
    showMoreButton: {
      ...baseRow,
      justifyContent: "center",
      marginTop: normalize(16),
      paddingVertical: normalize(8),
    },
    showMoreText: {
      fontSize: normalize(15),
      color: "#004EA2",
      fontWeight: "bold",
      marginRight: normalize(4),
    },
    usefulLinksContainer: { marginBottom: normalize(10) },
    usefulLinksWrapper: {
      paddingHorizontal: normalize(16),
      gap: normalize(12),
    },
    usefulLinkCard: {
      ...baseRow,
      backgroundColor: "#f1f5fb",
      borderRadius: normalize(12),
      paddingVertical: normalize(16),
      paddingHorizontal: normalize(16),
    },
    usefulLinkIcon: { marginRight: normalize(12) },
    usefulLinkLabel: {
      flex: 1,
      fontSize: normalize(16),
      color: "#111",
      fontWeight: "500",
    },
    noticeListContainer: { marginBottom: normalize(32) },
    noticeCard: {
      marginHorizontal: normalize(16),
      backgroundColor: whiteColor,
      borderRadius: normalize(16),
      padding: normalize(16),
      ...baseShadow,
      elevation: 2,
    },
    noticeItem: {
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
      paddingBottom: normalize(16),
      marginBottom: normalize(16),
    },
    noticeHeader: { ...baseRow, marginBottom: normalize(8) },
    noticeTag: {
      borderWidth: 1,
      borderColor: "#004EA2",
      borderRadius: normalize(12),
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(2),
      marginRight: normalize(12),
    },
    noticeTagText: {
      color: "#004EA2",
      fontSize: normalize(12),
      fontWeight: "bold",
    },
    noticeDate: { color: "#666", fontSize: normalize(13) },
    noticeBody: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
    },
    noticeTitle: {
      flex: 1,
      fontSize: normalize(15),
      fontWeight: "bold",
      color: "#111",
      lineHeight: normalize(22),
      paddingRight: normalize(8),
    },
    couponScroll: { paddingLeft: normalize(16), overflow: "visible" },
    couponCard: {
      width: normalize(160),
      backgroundColor: whiteColor,
      borderRadius: normalize(12),
      overflow: "hidden",
      marginRight: normalize(12),
      ...baseShadow,
      elevation: 2,
    },
    couponImage: { width: "100%", height: normalize(110) },
    couponTextContainer: {
      padding: normalize(14),
      minHeight: normalize(70),
      justifyContent: "center",
    },
    couponText: {
      fontSize: normalize(13),
      color: "#111",
      fontWeight: "bold",
      lineHeight: normalize(18),
    },
    onboardingContainer: {
      flex: 1,
      ...baseCenter,
      paddingHorizontal: normalize(30),
    },
    onboardingIconContainer: {
      width: normalize(100),
      height: normalize(100),
      borderRadius: normalize(50),
      backgroundColor: "#1c1c1e",
      ...baseCenter,
      marginBottom: normalize(24),
    },
    onboardingInnerIcon: { position: "absolute" },
    onboardingSubtitle: {
      color: whiteColor,
      fontSize: normalize(18),
      fontWeight: "600",
      textAlign: "center",
      marginBottom: normalize(16),
    },
    onboardingButton: {
      backgroundColor: mainColor,
      paddingVertical: normalize(16),
      paddingHorizontal: normalize(32),
      borderRadius: normalize(30),
      width: "100%",
      alignItems: "center",
    },
    onboardingButtonText: {
      color: whiteColor,
      fontSize: normalize(16),
      fontWeight: "bold",
    },
    onboardingFooter: { marginTop: normalize(24), gap: normalize(8) },
    privacyText: {
      color: "#666",
      fontSize: normalize(12),
      textAlign: "center",
    },
    ageText: { color: "#555", fontSize: normalize(11), textAlign: "center" },
    receiptContainer: { flex: 1, ...baseCenter },
    receiptLogo: { width: "30%", aspectRatio: 1, marginBottom: normalize(20) },
    receiptHeader: {
      fontSize: normalize(20),
      fontWeight: "bold",
      marginBottom: normalize(10),
    },
    camFillView: { height: "100%", width: "100%" },
    camFlipOverlay: {
      position: "absolute",
      bottom: normalize(10),
      width: "100%",
      ...baseCenter,
    },
    camFlipButton: {
      width: "10%",
      height: "auto",
      ...baseCenter,
      borderColor: whiteColor,
      borderWidth: 2,
      borderRadius: normalize(50),
      aspectRatio: 1,
      padding: normalize(20),
    },
    qrCode: { backgroundColor: whiteColor, borderRadius: normalize(10) },
    chatInputRow: {
      height: "auto",
      width: "94%",
      ...baseRow,
      alignItems: "flex-end",
      justifyContent: "space-between",
      marginVertical: normalize(10),
    },
    chatSendButton: {
      width: "10%",
      height: "auto",
      ...baseCenter,
      backgroundColor: mainColor,
      borderRadius: normalize(50),
      aspectRatio: 1,
      padding: normalize(20),
    },
    pulseOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: secondaryColor,
      borderRadius: normalize(140),
    },
    processingContainer: {
      ...baseCenter,
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.4)",
    },
  });
};

// ─── Static Map Styles ────────────────────────────────────────────────────
// Extracted to be constant and avoid heavy re-renders on the Map component
export const MapStyles = StyleSheet.create({
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: normalizeFontSize(12),
    paddingHorizontal: normalizeFontSize(25),
    borderRadius: normalizeFontSize(100),
    borderWidth: 1,
    justifyContent: "center",
  },
  mapButtonText: {
    fontSize: normalizeFontSize(12),
    fontWeight: "600",
    marginLeft: normalizeFontSize(8),
  },
  mapContainer: { flex: 1 },
  mapView: { flex: 1 },
  mapWebContainer: { flex: 1, width: "100%", height: "100%" },
  mapModalOverlay: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    padding: normalizeFontSize(16),
    alignItems: "center",
    zIndex: 999,
  },
  mapModalContent: {
    backgroundColor: whiteColor,
    width: "100%",
    maxWidth: normalizeFontSize(500),
    borderRadius: normalizeFontSize(20),
    padding: normalizeFontSize(20),
    boxShadow: `0px 0px ${normalizeFontSize(20)}px rgba(0, 0, 0, 0.3)`,
    elevation: 20,
    overflow: "hidden",
  },
  mapModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: normalizeFontSize(5),
  },
  mapModalTitle: {
    fontSize: normalizeFontSize(18),
    fontWeight: "bold",
    color: "#2F3542",
    flexShrink: 1,
  },
  mapAreaBadge: {
    fontSize: normalizeFontSize(10),
    fontWeight: "800",
    textTransform: "uppercase",
  },
  mapCloseIcon: {
    fontSize: normalizeFontSize(20),
    color: "#ccc",
    padding: normalizeFontSize(5),
  },
  mapListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: normalizeFontSize(12),
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  mapDot: {
    width: normalizeFontSize(8),
    height: normalizeFontSize(8),
    borderRadius: normalizeFontSize(4),
    marginRight: normalizeFontSize(10),
  },
  mapListItemText: {
    flex: 1,
    fontSize: normalizeFontSize(15),
    color: "#333",
    fontWeight: "500",
  },
  mapArrow: { color: "#ccc", fontSize: normalizeFontSize(18) },
  mapBackArrow: {
    fontSize: normalizeFontSize(22),
    color: "#333",
    marginRight: normalizeFontSize(5),
  },
  mapDesc: {
    fontSize: normalizeFontSize(14),
    color: "#57606F",
    lineHeight: normalizeFontSize(20),
    marginBottom: normalizeFontSize(15),
  },
  mapInfoRow: { flexDirection: "row", marginBottom: normalizeFontSize(6) },
  mapLabel: {
    width: normalizeFontSize(60),
    fontSize: normalizeFontSize(13),
    color: "#aaa",
    fontWeight: "600",
  },
  mapValue: {
    flex: 1,
    fontSize: normalizeFontSize(13),
    color: "#333",
    fontWeight: "500",
  },
  mapFooter: {
    marginTop: normalizeFontSize(20),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    flexWrap: "wrap",
    gap: normalizeFontSize(8),
  },
  mapBtnPrimary: {
    backgroundColor: "#2F3542",
    paddingVertical: normalizeFontSize(10),
    paddingHorizontal: normalizeFontSize(20),
    borderRadius: normalizeFontSize(8),
  },
  mapBtnText: {
    color: whiteColor,
    fontWeight: "bold",
    fontSize: normalizeFontSize(14),
  },
});
